sudo: required
language: ruby
bundler_args: --without development

before_install:
  - gem install bundler
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.2.deb
  - sudo service elasticsearch start

before_script:
  - psql -c 'create database opencourts_test;' -U postgres
  - "cp config/configuration.yml.travis config/configuration.yml"
  - "cp config/database.yml.example config/database.yml"
  - bundle exec rake db:schema:load

script:
  - bundle exec rspec spec

addons:
  postgresql: '9.1'
