defaults: &defaults
  # Storage configuration
  storage:

    # Storage root path
    root: 'storage'

  # Resources configuration
  resource:

    # List of resources updateable by crawlers
    updateable: [Court, Judge, Hearing, Decree]

  # Extractor configuration
  extractor:

    image:
      # Perform image extraction on specified resources if possible
      perform: [Decree]

      # Override existing image extractions for specified resources
      override: []

    text:
      # Perform text extraction on specified resources if possible
      perform: [Decree]

      # Override existing text extractions for specified resources
      override: []

development:
  <<: *defaults 

  extractor:
    image:
      perform: []

test:
  <<: *defaults

  resource:
    updateable: [Court, Judge]

staging:
  <<: *defaults

  resource:
    updateable: [Court, Judge]

production:
  <<: *defaults

  resource:
    updateable: [Court, Judge, Decree]

  extractor:
    image:
      perform: []
