---
:concurrency: 20
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 0
production:
  :concurrency: 20
:queues:
  - [decree-listers,   2]
  - [hearing-listers,  1]
  - [decree-crawlers,  6]
  - [hearing-crawlers, 1]
#:limits:
#  decree-listers:   6
#  hearing-listers:  6
#  decree-crawlers:  4
#  hearing-crawlers: 4
